CREATE DATABASE TESTDB;

USE TESTDB;

CREATE TABLE USERS (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(30) NOT NULL
);

INSERT INTO USERS (username) VALUES ('admin');
INSERT INTO USERS (username) VALUES ('tester');